apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      volumes: # Define volume
        - name: shared-logs
          persistentVolumeClaim:
            claimName: log-storage-claim
      containers:
        - name: pingpong
          image: pingpong:002536
          imagePullPolicy: IfNotPresent
          volumeMounts: # Mount volume
            - name: shared-logs
              mountPath: /app/data
