apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      volumes: # Define volume
        - name: shared-logs
          persistentVolumeClaim:
            claimName: project-storage-claim
      containers:
        - name: webserver
          image: webserver:224127
          imagePullPolicy: IfNotPresent
          volumeMounts: # Mount volume
            - name: shared-logs
              mountPath: /app/data

          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "250m"

          env:
            - name: PORT
              value: "3001"

            - name: PICTURE_URL
              value: "https://picsum.photos/400"
