apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      volumes: # Define volume
        - name: shared-logs
          persistentVolumeClaim:
            claimName: project-storage-claim
      containers:
        - name: webserver
          image: webserver:230823
          imagePullPolicy: IfNotPresent
          volumeMounts: # Mount volume
            - name: shared-logs
              mountPath: /app/data

          env:
            - name: PORT
              value: "3001"
